version: '3.7'

services:
  express:
    image: jmuppala/node-server
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "start"]
    stdin_open: true
  mongodb:
    image: jmuppala/mongo-server