version: '3.7'

services:
  nodeapp:
    build:
      context: .
    command: nodemon -L ./bin/www
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules: